### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AndrewDryga** [Nebo15/sage#1]
- [x] Make sure all error messages are clean and have no spelling mistakes
- [x] Make readme and module docs are clean and have no spelling mistakes
- [x] Form a simple terminology (eg. use hook for finally) to make docs simpler to understand
- [ ] Write sample compensation adapter that retries failed compensations over time
- [ ] Create Sage.Operation protocol and refactor existing function operations to work on top of it
- [x] Implement simple Retry policies to hook into Sage and let it be extendable
- ~Implement simple Cache policies to hook into Sage and let it be extendable~
- [x] Get more feedback from friends :)
